### ISSUE TITLE
Shader Error - Unity 5.6.2f1

### ISSUE THREAD

**Issue by hacaro76** [H-man/UnityVertexColors#1]
Shader error in 'Standard (Vertex Color)': Duplicated input semantics can't change type, size, or layout ('TEXCOORD8'). at Assets/Shaders/UnityVC.cginc(197) (on glcore)

Compiling Vertex program with DIRECTIONAL _NORMALMAP _VERTEXCOLOR _PARALLAXMAP _SPECULARHIGHLIGHTS_OFF
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA

**Comment by H-man** [comment]
Sorry, I don't currently have Unity 5.6 version. 

I updated and tested with unity 2017.1.1f1 version (check that branch) and couldn't replicate this, so I'm going to close this for now as I don't have possibility to check and fix the problem with 5.6 version
